from __future__ import annotations

from enum import Enum
from typing import Any


class ErrorCode(str, Enum):
    PROTOCOL_INVALID = "PROTOCOL_INVALID"
    PROTOCOL_VERSION_UNSUPPORTED = "PROTOCOL_VERSION_UNSUPPORTED"
    CAPABILITY_UNKNOWN = "CAPABILITY_UNKNOWN"
    POLICY_DENIED = "POLICY_DENIED"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    ARGUMENT_INVALID = "ARGUMENT_INVALID"
    PATH_OUTSIDE_ALLOWED_ROOT = "PATH_OUTSIDE_ALLOWED_ROOT"
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    DESTINATION_EXISTS = "DESTINATION_EXISTS"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    PLATFORM_UNSUPPORTED = "PLATFORM_UNSUPPORTED"
    TIMEOUT = "TIMEOUT"
    DUPLICATE_REQUEST = "DUPLICATE_REQUEST"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    REMOTE_RATE_LIMITED = "REMOTE_RATE_LIMITED"
    REMOTE_PERMISSION_DENIED = "REMOTE_PERMISSION_DENIED"
    REMOTE_REJECTED = "REMOTE_REJECTED"
    REMOTE_UNAVAILABLE = "REMOTE_UNAVAILABLE"
    REMOTE_RESPONSE_INVALID = "REMOTE_RESPONSE_INVALID"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    PLANNER_UNAVAILABLE = "PLANNER_UNAVAILABLE"
    PLANNER_FAILED = "PLANNER_FAILED"
    PLANNER_TIMEOUT = "PLANNER_TIMEOUT"
    PLANNER_OUTPUT_INVALID = "PLANNER_OUTPUT_INVALID"
    PLANNER_OUTPUT_TOO_LARGE = "PLANNER_OUTPUT_TOO_LARGE"
    AGENT_SESSION_NOT_FOUND = "AGENT_SESSION_NOT_FOUND"
    AGENT_SESSION_INVALID = "AGENT_SESSION_INVALID"
    AGENT_SESSION_BUSY = "AGENT_SESSION_BUSY"
    AGENT_STATE_INVALID = "AGENT_STATE_INVALID"


class LainError(Exception):
    def __init__(self, code: ErrorCode, message: str, *, details: dict[str, Any] | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}

    def to_dict(self) -> dict[str, Any]:
        return {
            "error": {
                "code": self.code.value,
                "message": self.message,
                "details": self.details,
            }
        }
